# Commands
# Accounts
### Create Account Steven
POST http://localhost:6006/opportunity/create/account/b3bc5991-5aec-4dde-8f6e-123456789012/Steven

### Create Account Ted
POST http://localhost:6006/opportunity/create/account/369eb3e1-128f-4e3b-be77-098765432109/Ted

### Create Account David
POST http://localhost:6006/opportunity/create/account/369eb3e1-128f-4e3b-be77-000000000000/David

# Opportunities/Quotes
### Open Opportunity for Steven

POST http://localhost:6006/opportunity/open
Content-Type: application/json

{
  "accountId": "b3bc5991-5aec-4dde-8f6e-123456789012",
  "opportunityId": "2718e75e-a70d-4d61-8e30-999888777666",
  "name": "Opportunity-A",
  "value": 42,
  "endDate": "2024-04-12T16:55:41.261+00:00"
}

### Open Opportunity for Ted

POST http://localhost:6006/opportunity/open
Content-Type: application/json

{
  "accountId": "369eb3e1-128f-4e3b-be77-098765432109",
  "opportunityId": "4b8a7047-2ebd-4d79-b835-111222333444",
  "name": "Opportunity-B",
  "value": 1337,
  "endDate": "2024-04-12T16:55:41.261+00:00"
}

### Open Opportunity for David, that should close very soon due to the end date...

POST http://localhost:6006/opportunity/open
Content-Type: application/json

{
  "accountId": "369eb3e1-128f-4e3b-be77-000000000000",
  "opportunityId": "86f26a49-3940-4506-a1f8-000111999222",
  "name": "Opportunity-C",
  "value": 10000,
  "endDate": "2024-03-13T10:00:00.261+00:00"
}

### Pitch Quote for Steven

POST http://localhost:6006/opportunity/pitch
Content-Type: application/json

{
  "opportunityId": "2718e75e-a70d-4d61-8e30-999888777666",
  "name": "Okay Quote",
  "validUntil": "2024-03-14T16:55:41.261+00:00",
  "products": [
    {
      "productId": "1618c594-af9f-4234-b90b-637c51b54c22",
      "catalogId": 1,
      "quantity": 3,
      "amount": 60
    }
  ]
}

### Pitch Quote for Ted

POST http://localhost:6006/opportunity/pitch
Content-Type: application/json

{
  "opportunityId": "4b8a7047-2ebd-4d79-b835-111222333444",
  "name": "Very Interesting Quote",
  "validUntil": "2024-03-20T16:55:41.261+00:00",
  "products": [
    {
      "productId": "1618c594-af9f-4234-b90b-637c51b54c22",
      "catalogId": 1,
      "quantity": 2,
      "amount": 40
    },
    {
      "productId": "4595aac1-36a8-4f95-9857-9784fc7214cf",
      "catalogId": 2,
      "quantity": 7,
      "amount": 175
    }
  ]
}

### Add product to Steven's Quote, which fails as the product is not known
POST http://localhost:6006/opportunity/2718e75e-a70d-4d61-8e30-999888777666/quote/58600df5-ac6e-4a2b-8529-5322ef357497/add
Content-Type: application/json

{
  "productId": "00000000-0000-0000-0000-000000000000",
  "catalogId": -1,
  "quantity": 10,
  "amount": 600
}

### Add product to Steven's Quote, which fails as there are insufficient of these product in stock
POST http://localhost:6006/opportunity/2718e75e-a70d-4d61-8e30-999888777666/quote/c4dcd3ea-6ac0-4be4-bd65-755582e7afc1/add
Content-Type: application/json

{
  "productId": "c8da3f64-b111-472e-bbac-396dbe99b57f",
  "catalogId": 5,
  "quantity": 9001,
  "amount": 1000000
}

### Add product to Ted's Quote, successfully
POST http://localhost:6006/opportunity/4b8a7047-2ebd-4d79-b835-111222333444/quote/f01b186c-d5a2-4862-a71c-380886d3da11/add
Content-Type: application/json

{
  "productId": "74fed045-96fe-4375-9736-98e789644836",
  "catalogId": 3,
  "quantity": 3,
  "amount": 2000000
}

### Approve Ted's Quote
POST http://localhost:6006/opportunity/4b8a7047-2ebd-4d79-b835-111222333444/quote/f01b186c-d5a2-4862-a71c-380886d3da11/approve

### Reject Steven's Quote
POST http://localhost:6006/opportunity/2718e75e-a70d-4d61-8e30-999888777666/quote/c4dcd3ea-6ac0-4be4-bd65-755582e7afc1/reject

###
# Queries
### Get all Deal Insights
GET http://localhost:6006/opportunity/deal-insights

### Get Opportunity by Name
# Steven's Opportunity Summary
GET http://localhost:6006/opportunity/name/Opportunity-A

###
# Ted's Opportunity Summary
GET http://localhost:6006/opportunity/name/Opportunity-B

### Get Opportunities by Account Id
# Steven's Opportunities
GET http://localhost:6006/opportunity/account/b3bc5991-5aec-4dde-8f6e-123456789012

###
# Ted's Opportunities
GET http://localhost:6006/opportunity/account/369eb3e1-128f-4e3b-be77-098765432109

### Get Opportunities by Stage
# RFP
GET http://localhost:6006/opportunity/stage/RFP

###
# Pitched
GET http://localhost:6006/opportunity/stage/PITCHED

###
# Closed Won
GET http://localhost:6006/opportunity/stage/CLOSED_WON

###
# Closed Lost
GET http://localhost:6006/opportunity/stage/CLOSED_LOST
