version: '3.8'
services:
  axonserver-1:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-1
    environment:
      axoniq_axonserver_hostname: axonserver-1
      axoniq_axonserver_autocluster_first: axonserver-1
      axoniq_axonserver_autocluster_contexts: _admin,opportunity
      server_port: 8024
      axoniq_axonserver: PORT=8124
    volumes:
      - axonserver-1-log:/axonserver/log
      - axonserver-1-events:/axonserver/events
      - axonserver-1-data:/axonserver/data
      - ./axoniq-server.license:/axonserver/config/axoniq.license
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net

  axonserver-2:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-2
    environment:
      axoniq_axonserver_hostname: axonserver-1
      axoniq_axonserver_autocluster_first: axonserver-1
      axoniq_axonserver_autocluster_contexts: _admin,opportunity
      server_port: 8025
      axoniq_axonserver_port: 8125

    volumes:
      - axonserver-2-log:/axonserver/log
      - axonserver-2-events:/axonserver/events
      - axonserver-2-data:/axonserver/data
      - ./axoniq-server.license:/axonserver/config/axoniq.license
    ports:
      - '8025:8025'
      - '8125:8125'
      - '8225:8225'
    networks:
      - axon-net

  axonserver-3:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-3
    environment:
      axoniq_axonserver_hostname: axonserver-1
      axoniq_axonserver_autocluster_first: axonserver-1
      axoniq_axonserver_autocluster_contexts: _admin,opportunity
      server_port: 8026
      axoniq_axonserver_port: 8126
    volumes:
      - axonserver-3-log:/axonserver/log
      - axonserver-3-events:/axonserver/events
      - axonserver-3-data:/axonserver/data
      - ./axoniq-server.license:/axonserver/config/axoniq.license
    ports:
      - '8026:8026'
      - '8126:8126'
      - '8226:8226'
    networks:
      - axon-net

volumes:
  axonserver-1-log:
    driver: local
  axonserver-1-events:
    driver: local
  axonserver-1-data:
    driver: local
  axonserver-2-log:
    driver: local
  axonserver-2-events:
    driver: local
  axonserver-2-data:
    driver: local
  axonserver-3-log:
    driver: local
  axonserver-3-events:
    driver: local
  axonserver-3-data:
    driver: local

networks:
  axon-net: