version: '3.8'
services:
  axonserver-1:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-1
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/as-cluster-template.yml
      - AXONIQ_AXONSERVER_ENTERPRISE_LICENSE-DIRECTORY=/axonserver
      - SERVER_PORT=8024
      - AXONIQ_AXONSERVER_PORT=8124
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-1-log:/axonserver/log
      - axonserver-1-events:/axonserver/events
      - axonserver-1-data:/axonserver/data
      - ./axoniq.license:/axonserver/axoniq.license
      - ./as-cluster-template.yml:/axonserver/as-cluster-template.yml
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net

  axonserver-2:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-2
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/as-cluster-template.yml
      - AXONIQ_AXONSERVER_ENTERPRISE_LICENSE-DIRECTORY=/axonserver
      - SERVER_PORT=8025
      - AXONIQ_AXONSERVER_PORT=8125
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-2-log:/axonserver/log
      - axonserver-2-events:/axonserver/events
      - axonserver-2-data:/axonserver/data
      - ./axoniq.license:/axonserver/axoniq.license
      - ./as-cluster-template.yml:/axonserver/as-cluster-template.yml
    ports:
      - '8025:8025'
      - '8125:8125'
      - '8225:8225'
    networks:
      - axon-net

  axonserver-3:
    image: axoniq/axonserver:latest-jdk-17-dev
    hostname: axonserver-3
    environment:
      - AXONIQ_AXONSERVER_CLUSTERTEMPLATE_PATH=/axonserver/as-cluster-template.yml
      - AXONIQ_AXONSERVER_ENTERPRISE_LICENSE-DIRECTORY=/axonserver
      - SERVER_PORT=8026
      - AXONIQ_AXONSERVER_PORT=8126
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-3-log:/axonserver/log
      - axonserver-3-events:/axonserver/events
      - axonserver-3-data:/axonserver/data
      - ./axoniq.license:/axonserver/axoniq.license
      - ./as-cluster-template.yml:/axonserver/as-cluster-template.yml
    ports:
      - '8026:8026'
      - '8126:8126'
      - '8226:8226'
    networks:
      - axon-net

volumes:
  axonserver-1-log:
  axonserver-1-events:
  axonserver-1-data:
  axonserver-2-log:
  axonserver-2-events:
  axonserver-2-data:
  axonserver-3-log:
  axonserver-3-events:
  axonserver-3-data:

networks:
  axon-net: